services:
  app:
    image: 'learn_spring_security_img:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/LEARN_SPRING_SECURITY
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: learn_spring_security_db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=LEARN_SPRING_SECURITY
    ports:
      - "65000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: